### ISSUE TITLE
Parser for Study Notices for Core Add-on (and HTML being shipped via RemoteSettings)

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-core-addon#167]
Parser for Study Notices (and HTML being shipped via RemoteSettings)

**Comment by Dexterp37** [comment]
@marniepw @rhelmer  is this about the parser for `about:ion` in Firefox or something to be added to the core-addon?

If the former, what if we add a label or something to avoid the confusion? Maybe `legacy`? ;-)

**Comment by marniepw** [comment]
Yep, I believe it's the same as this: https://bugzilla.mozilla.org/show_bug.cgi?id=1676333

**Comment by Dexterp37** [comment]
> 
> 
> Yep, I believe it's the same as this: https://bugzilla.mozilla.org/show_bug.cgi?id=1676333

Ok, because I believe that @rhelmer and @knowtheory settled on a different strategy for the core addon. @rhelmer would you mind explaining it here?

**Comment by knowtheory** [comment]
The core question for this ticket is whether or not we intend to ship program metadata via RemoteSettings, or if updates to the study listing, program notice, and study notices are shipped as changes in the Core Addon codebase.

The primary consideration is what the fix-deploy pipeline will be.

**Comment by rhelmer** [comment]
I think the details here are (since we're not using Firefox but pulling from RS directly):

- should we use content signing for RS responses? (we probably should but is it a blocker?)
- how often do we fetch RS in the background?
- will AMO reviewers let us pull HTML from remote?

The most important benefits we get:

1. remote content delivery
2. ship new studies / kill-switch for existing studies

So I think even if we can't do (1), (2) is still valuable. We just need to make sure we know what our constraints are.

**Comment by hamilton** [comment]
Closing this issue in favor of subsequent discussions. We're likely to use another approach than this one.
