### ISSUE TITLE
User/visitor can sign up for email updates about Rally  

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-core-addon#176]
How are we capturing user's email addresses? Where do those live? How are they accessed?

Prior art: https://docs.google.com/document/d/1sviXUV6jLqDW2gWbLItN6x-oaWj9wm-gSxNQUM5Jh0c/edit

**Comment by javaun** [comment]
Summarizing in the doc above (and from our conversation w/ the newsletter/marketing teams)

There are three main requirements here for email signups. 

- **Chrome waiting list**
- Product / news updates (these are treated as marketing updates) 
- Partner list (may just be an email)

The pure MVP is just the first one. The purpose of the chrome list is to capture the intent from people who would've enrolled during our GTM campaign, but could not because we're not on their platform. It is not a promise to serve other browsers (i.e. Chrome, Edge, Safari), but is a baseline metric to tell us how many users we're leaving on the table. 

The requirement is not to be able to send to these users at GTM, just to be able to capture them.

Our paths here are to either standup a third party tool like Mailchimp (or dump this into another legal approved database), or to go into the existing marketing newsletter system. Lauren proposed that we could do this in 2 weeks, and avoid tech debt on etiher side. Javaun is meeting w/ Brynn Haack on 12/3. If we can do something minimal, it's probably an email form that we link to from our website. The resourcing is presumed to be outside the Ion/Threespot teams.

**Comment by javaun** [comment]
Here is v1 of the MUF (Minimal ugly form) for waitlist and email newsletter capture

https://docs.google.com/forms/d/e/1FAIpQLSd1o4rJhRdg0F6hwfUSI3h1yDArb-UcoxI6rMH2jWF6HzUiqg/viewform
cc @hamilton

**Comment by marniepw** [comment]
Meeting with vendor 2/17. Will know more tomorrow.

**Comment by marniepw** [comment]
Closing. Will be replaced with other, more specific issues (i.e., newsletter signup ticket).
