### ISSUE TITLE
rally toolbar icon works with web-ext run, but not if I build the add-on and sideload it

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#339]
cc @rhelmer – just noticed this after running `npm run build` on `master`. Could you possibly attempt to replicate this?

**Comment by Dexterp37** [comment]
I can't seem to be able to reproduce this.
![image](https://user-images.githubusercontent.com/883721/107199460-bdac7780-69f6-11eb-8000-f4db7da911de.png)

@hamilton would you kindly provide clearer STR?

**Comment by rhelmer** [comment]
> cc @rhelmer – just noticed this after running `npm run build` on `master`. Could you possibly attempt to replicate this?

I suspect that it has to do with privileged extension loading - @hamilton if you use `web-ext` it should just work, because we specify the extra pref you need in https://github.com/mozilla-rally/rally-core-addon/blob/master/web-ext-config.js#L14

If you're loading from `about:debugging` then that's all you should need ^ if you're loading it directly you also need the `xpinstall.signatures.required` pref set to `false`

**Comment by rhelmer** [comment]
Oh, and also take a look at the various debug consoles - the one you get by inspecting the add-on from `about:debugging` runs in the context of the background script so that's pretty useful, the usual web developer console can be used on `moz-extension://` pages.

**Comment by hamilton** [comment]
Yep, this was fixed w/ the pref.
