### ISSUE TITLE
Add the study template demo to the Remote Settings

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#348]
Before we can start using our next release, we need to make sure that the Rally Basic Demo / Study template demo is availalbe in the study list (remote settings). We need to move away from testing with a local list of addons to test the _real thing_.

If we add the idem, would we be able to remove it before alpha?
While doing this should we also simplify the remote settings schema a bit?
Do we have docs/should we have docs for the team to add/edit/remove things from that list?

@rhelmer what do you think?

**Comment by rhelmer** [comment]
> Before we can start using our next release, we need to make sure that the Rally Basic Demo / Study template demo is availalbe in the study list (remote settings). We need to move away from testing with a local list of addons to test the _real thing_.
> 
> If we add the idem, would we be able to remove it before alpha?

Yes, if we're implementing things correctly we should be able to add/remove records and have it work properly.

> While doing this should we also simplify the remote settings schema a bit?

Sure, I actually have a branch where I've been doing this for the kill-switch work, but I can go ahead and separate that out so we can move on this now.

> Do we have docs/should we have docs for the team to add/edit/remove things from that list?

I have some docs from the Ion days that I could use as a starting point, it's pretty simple once we have the collections and schema set up for folks to go in and modify data at that point via the admin UI.

> 
> @rhelmer what do you think?

I will go ahead and take this issue if you don't mind, since I feel like I have the starting point for the docs and schema already :) I'll open a PR you can take a look at before we send it to r-s server folks.

**Comment by Dexterp37** [comment]
Thanks!

**Comment by rhelmer** [comment]
This is live on production and stage now: https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/rally-studies-v1/records
