### ISSUE TITLE
update routing and success messaging after updating profile

### ISSUE THREAD

**Issue by changecourse** [mozilla-rally/rally-core-addon#394]
Upon updating your profile (and clicking save changes) someone should be rerouted back to the current studies page, where a toast is presented confirming their updated changes (screenshot below). Additionally, if someone chooses to "cancel" from the manage profile screen, they should also be rerouted back to the Current Studies page (with no toast).

<img width="1200" alt="add-on_ current studies (profile updated)" src="https://user-images.githubusercontent.com/6164801/107801348-2f4d3400-6d1d-11eb-9a10-72865fa5b158.png">

**Comment by hamilton** [comment]
This will require completing #188 to land, but I think one PR can accomplish all of these and also give us more leverage for other toasts going forward. I put together a [Svelte REPL](https://svelte.dev/repl/bc32b35b4bb24bfdb93b1d89bb2eafbc?version=3.32.2) this morning based on someone else's that has the functionality we need here.

This entails:
- porting the above REPL into a special `notification` frontend store + `NotificationSystem.svelte` component (we can decouple this from the main app store since it is ephemeral)
- integrating the callback into the current `StudyCard` implementation
- patching in the `notification.send("profile successfully updated")` part in the callback for the Manage Profile page
- writing a short suite of unit tests for this new notification store so we have more trust in it going forward
