### ISSUE TITLE
Fix or disable 'livereload' 

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/rally-core-addon#498]
In #295 we watch the generated Svelte code for changes. In order to compile Svelte when the raw code changes, we use the watch option in rollup. That, in turn, makes the Svelte compiler run in watch mode, spinning up a server and injecting a script in the content that reloads the page. Unfortunately, this doesn't work in the addon, due to the security sandboxing.

We should either find a way to make it work or disable the livereload, while keeping code watch available.

**Comment by rhelmer** [comment]
I think removing livereload would be pretty easy:
https://github.com/mozilla-rally/rally-core-addon/blob/master/rollup.config.js#L94-L96

However taking a shot at getting it working seems worth it :) It would allow hacking on Svelte code without the whole extension being reloaded.

> Unfortunately, this doesn't work in the addon, due to the security sandboxing.

At least part of the problem is that Svelte seems to be using the base URL for the site and just sticking a port number at the end of it, such as: `moz-extension://c10f4c4d-be8c-c848-921a-cfbac21aa872:35729/livereload.js?snipver=1`

That is clearly not going to do anything useful :) If it used `http://localhost:35729/livereload.js?snipver=1` then it stands some chance of being working, but as you mention I would not be at all surprised if security sandboxing prevents this sort of thing.
