### ISSUE TITLE
move the add-on toolbar icon back into the “unprivileged” location

### ISSUE THREAD

**Issue by changecourse** [mozilla-rally/rally-core-addon#98]
<img width="413" alt="Screen Shot 2020-10-20 at 9 36 00 AM" src="https://user-images.githubusercontent.com/6164801/96609381-b3376800-12b7-11eb-99a9-b519ff5193c0.png">

Moving the add-on toolbar location to where all other add-on icons live, to the right of the main menu.

**Comment by rhelmer** [comment]
I think we will basically get this "for free", only the built-in Firefox about:ion uses this icon (it appears when the Pioneer ID pref is set technically).

@Dexterp37 removed the need to have this pref set in order to send encrypted telemetry so the Ion/Rally ID will be stored in the core add-on, and the core add-on will not have a choice as to where the toolbar icon appears so it should be in the standard unprivileged location.

Anything I am missing @Dexterp37 ?

**Comment by Dexterp37** [comment]
> @Dexterp37 removed the need to have this pref set in order to send encrypted telemetry so the Ion/Rally ID will be stored in the core add-on, and the core add-on will not have a choice as to where the toolbar icon appears so it should be in the standard unprivileged location.
> 
> Anything I am missing @Dexterp37 ?

No, I don't think you are. Just a note that, while the change to provide a Ion/Rally ID to the submission APIs is present in Firefox, the core addon is not using that change, yet :-)

**Comment by rhelmer** [comment]
I don't think there's really any action for us to take on the core add-on here. If we want to change this in Firefox we can, @changecourse wdyt?

**Comment by changecourse** [comment]
@rhelmer I'm not concerned about us adjusting this for about:ion

If we are good to go by default for our new Rally experience, we can close this issue :)
